### PR TITLE
sony: loire: Remove libbt vendor config

### PR DESCRIPTION
**Pull request by humberos**
It is not necessary anymore since the bcm driver has
direct calls to the methods that would also be triggered
by writing to the corresponding device nodes.

All vendor configuration should be loaded
from system/etc/bluetooth/bt_vendor.conf

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I135a6864e01ed45f8d02e4a9e4a7f56314cbc6ba

### CODE REVIEW

**Comment by humberos** [comment]
ping @Diewi @oshmoun @rcstar6696

**Comment by oshmoun** [comment]
yes this works!
no more bt+fm breakage when controlling bt  while fm is on 👍

**Comment by rcstar6696** [comment]
@oshmoun  what was your mistake ? maybe it can help if it was working

**Comment by oshmoun** [comment]
eh I had the libbt patch still in the build, stupid mistake 😓

**Pull request closed without merging**
