### PR TITLE
loire: disable Fluence

### PR DESCRIPTION
**Pull request by alviteri**
TEMP hack until fix ....

needs
https://android-review.googlesource.com/#/c/390996/

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by humberos** [comment]
@alviteri 
https://gerrit.omnirom.org/#/c/23408/

**Comment by humberos** [comment]
and yes, fluence should be disabled.

**Comment by alviteri** [comment]
Hi @humberos already did that but I prefer touch HAL ... Anyway we need see why fluence is not working here and probably add the correct patch ......

**Comment by jerpelea** [comment]
omni way is cleaner untill we find a better one

please pr in both devices

**Pull request closed without merging**
