### PR TITLE
fstab: Split into early and latemount, reserve 128M on /data

### PR DESCRIPTION
**Pull request by ix5**
**VERIFY ME!** Calling @oshmoun and other loire owners.

Makes things neater with the stage-separated mounting logic in Q and later.

### CODE REVIEW

**Comment by chris42** [comment]
Works on Kugo, still booting

**Comment by ix5** [comment]
@chris42 is that on Android 10, with https://github.com/sonyxperiadev/device-sony-common/pull/751 applied?

How about with FDE encryption enabled? It should be standard, but some people disable it.

**Comment by chris42** [comment]
@ix5 yes to android 10, #751 was not applied, as it was a build overnight.
In this build FDE is disabled.

So I guess you want me to retest with #751 applied and FDE enabled? ;-)

**Comment by ix5** [comment]
Please do

**Comment by chris42** [comment]
So the fstab changes are not an issue and will work with q-mr1-legacy. However the connected sonyxperiadev/device-sony-common#751 is something else. See comment over there.

**Comment by MarijnS95** [comment]
@chris42 Correct, if `mount_all` has no argument passed it'll mount everything in fstab, which would otherwise be split by passing `--early` and `--late`.

**Pull request merged**
